package org.conf.parameters;

public enum ReturnCodes {
	EXIT_ON_SUCCESS(0),
	EXIT_ON_UNKNOWN_ERROR(-1),
	MISSION_NULL_EXIT_CODE(100),
	TW_NULL_EXIT_CODE(101),
	LINK_MISSION_NOT_FOUND(555),
	RATE_OUT_OF_BOUND(32),
	LASER_HEAD_NOT_FOUND(31),
	PHEROMONE_SPREAD_ERROR(500), 
	EXIT_RESERVATION_ERROR(1000), 
	STRADDLECARRIER_NOT_FOUND(50), 
	EXIT_ON_NULL_TIME_SCHEDULER(10),
	EXIT_ON_X_COORD_ERROR(20), 
	EXIT_ON_Y_COORD_ERROR(21),
	LASER_HEAD_RANGE_ERROR(32), EXIT_ON_NULL_MODEL_ERROR(40), EXIT_ON_NULL_SPEED_CHARACTERITICS(41), 
	EXIT_ON_TIMEWINDOW_ERROR(102), EXIT_ON_SLOT_RESERVATION_ERROR(1024), EXIT_NULL_RESERVATION_ERROR(1025), EXIT_ON_CONTAINER_NOT_FOUND_ERROR(60);
	
	private int code;
	
	private ReturnCodes(int code){
		this.code = code;
	}
	
	public int getCode(){
		return this.code;
	}
	
	public String toString(){
		return this.name()+":"+this.code;
	}
}
